#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "header.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /*REG_DISPCNT = 0x0403;
  videoBuffer[OFFSET(120, 80, 240)] = 0x001F;
  videoBuffer[OFFSET(136, 80, 240)] = 0x03E0;
  videoBuffer[OFFSET(120, 96, 240)] = 0x7C00;
  while(1);*/
  printf("%d", myVar);
  return 0;
}
